# Generated by Django 4.2.1 on 2023-05-31 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_doc', models.CharField(max_length=30)),
                ('description_tipo', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Numeracao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_doc', models.IntegerField()),
                ('description_doc', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo')),
            ],
            options={
                'verbose_name': 'Numero',
                'verbose_name_plural': 'Numeros',
                'ordering': ['id'],
            },
        ),
    ]
